#line 2 "cool-lex.cc"

#line 4 "cool-lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[306] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       74,   72,   71,   71,    1,   66,   67,   57,   54,   63,
       56,   61,   55,   51,   65,   64,   59,   58,   68,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   69,   70,   62,   12,    9,    2,   73,   11,
       19,   18,   25,   24,   25,   25,   16,   13,   14,   16,
       20,   21,   17,   51,   53,   60,   52,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   28,   28,   29,
       30,   44,   29,   30,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   39,   39,   44,   44,   44,   44,   44,
       44,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   28,   45,   28,   29,   30,   45,
       29,   30,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   39,   39,   45,   45,   45,   45,   45,   45,   45,
       45,   12,    7,    8,    3,    6,    5,    4,    7,   19,
       23,   22,   15,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   32,   32,   44,   44,   40,
       40,   44,   44,   44,   44,   44,   44,   44,   44,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   32,   45,   32,   45,   40,
       45,   40,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   37,   37,   44,   44,   27,   27,   38,   38,   44,
       44,   44,   44,   33,   33,   34,   34,   35,   35,   44,
       44,   45,   37,   45,   37,   45,   27,   38,   27,   45,
       38,   45,   45,   45,   45,   45,   45,   33,   33,   34,
       34,   35,   42,   35,   42,   45,   45,   26,   26,   44,
       44,   44,   44,   36,   36,   45,   26,   26,   45,   43,
       43,   45,   45,   45,   45,   36,   36,   44,   44,   41,
       41,   45,   45,   41,   45,   41,   44,   44,   45,   45,

       31,   31,   31,   31,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,    1,   19,   20,   21,   22,   23,   24,   25,
       21,   26,   27,   21,   21,   28,   21,   29,   30,   31,
       21,   32,   33,   34,   35,   36,   37,   21,   21,   21,
        1,   38,    1,    1,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   49,   49,   50,   49,   51,
       52,   53,   49,   54,   55,   56,   57,   58,   59,   49,
       49,   49,   60,    1,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3
    } ;

static yyconst flex_uint16_t yy_base[313] =
    {   0,
        0,    0,   61,   63,  357,  356,   65,   66,   71,   73,
      358,  680,  680,  680,  680,  350,  680,  350,  680,  680,
      345,  680,  680,  341,  680,  680,   68,  335,  680,  114,
       60,   53,   56,   62,   68,  150,   57,   54,   67,   68,
      190,  297,  230,  150,  233,  232,  238,  242,  151,   66,
      237,  248,  680,  680,  680,    0,  680,  680,  261,  680,
        0,  680,  680,  680,  344,  344,  680,  680,  680,  316,
      680,  680,  680,  303,  680,  680,  680,  305,    0,   64,
       85,   97,  155,  144,  161,  152,  168,    0,    0,    0,
      228,  151,    0,  229,  220,  233,  249,  262,  268,  262,

      266,  286,  309,    0,    0,  314,  316,  227,  323,  321,
      322,  331,  260,  259,  358,  372,  360,  374,  362,  376,
      364,   35,  378,  371,    0,  372,  258,    0,  376,  367,
      256,  379,  373,  374,  380,  386,  394,  398,  402,  400,
      405,    0,  255,  410,  413,  420,  410,  426,  416,  421,
      427,    0,  680,  680,  680,  680,  680,  680,  680,    0,
      680,  680,  680,  428,  432,  430,  433,  450,  453,  456,
      457,  456,  459,  454,  456,    0,    0,  456,  458,    0,
        0,    0,    0,  462,  463,  463,  464,  467,  468,   68,
      477,  469,  481,  471,  483,  488,  495,   76,  498,  483,

      489,  499,  499,  504,  502,    0,  502,  254,  503,    0,
        0,  253,  252,  513,  514,  516,  522,  520,  528,  532,
      534,    0,    0,  532,  535,    0,    0,    0,    0,  538,
      541,  549,  550,    0,    0,    0,    0,    0,    0,  537,
      550,  136,    0,  545,  250,  546,    0,    0,  249,   78,
      204,  561,  562,  548,  561,  559,  572,    0,  197,    0,
      173,    0,    0,  143,  142,  572,  579,    0,    0,  577,
      580,  587,  588,    0,    0,  135,    0,  138,  137,    0,
      134,  581,  589,  588,  595,    0,  129,  585,  588,    0,
        0,  124,  590,    0,  592,   74,  600,  602,  604,  606,

        0,    0,    0,   67,  680,  661,  664,  667,  670,   78,
      673,  676
    } ;

static yyconst flex_int16_t yy_def[313] =
    {   0,
      305,    1,  306,  306,  307,  307,  308,  308,  309,  309,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
      305,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,  305,  305,  305,  310,  305,  305,  311,  305,
      312,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,   30,   30,   30,
       30,   78,   78,   30,   30,   78,   78,   30,   78,   30,
       30,   30,   78,   78,   78,   30,   30,   78,   78,   30,

       30,   78,   78,   30,   78,   30,   78,   30,   78,   30,
       78,   41,   41,   41,  112,  112,   41,   41,  112,  112,
       41,   41,   41,  112,  112,   41,   41,  112,  112,  112,
       41,   41,   41,  112,  112,   41,   41,  112,  112,   41,
       41,  112,   41,  112,   41,  112,  112,   41,   41,  112,
       41,  310,  305,  305,  305,  305,  305,  305,  305,  312,
      305,  305,  305,   30,   78,   30,   78,   30,   78,   30,
       78,   30,   78,   30,   78,   30,   78,   30,   78,   30,
       78,   30,   78,   30,   78,   30,   78,   30,   78,   41,
      112,  112,   41,   41,  112,  112,   41,   41,   41,  112,

       41,  112,  112,   41,   41,  112,  112,   41,   41,  112,
      112,   41,   41,  112,   41,  112,  112,   41,   41,  112,
       41,   30,   78,   30,   78,   30,   78,   30,   78,   30,
       78,   30,   78,   30,   78,   30,   78,   30,   78,   30,
       78,   41,  112,  112,   41,   41,  112,  112,   41,   41,
       41,  112,   41,  112,  112,   41,   41,  112,   41,  112,
       41,  112,  112,   41,   41,  112,   41,   30,   78,   30,
       78,   30,   78,   30,   78,   41,  112,   41,   41,  112,
       41,  112,  112,   41,   41,  112,   41,   30,   78,   30,
       78,   41,  112,  112,   41,   41,   30,   78,  112,   41,

       30,   78,  112,   41,    0,  305,  305,  305,  305,  305,
      305,  305
    } ;

static yyconst flex_uint16_t yy_nxt[744] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   12,   29,   30,
       30,   31,   30,   32,   33,   30,   34,   35,   36,   37,
       38,   30,   30,   39,   30,   30,   40,   12,   12,   41,
       42,   43,   42,   44,   45,   42,   42,   46,   42,   47,
       48,   49,   50,   42,   42,   51,   42,   42,   52,   53,
       54,   55,   12,   57,   58,   57,   58,   64,   64,   65,
       65,   66,   66,   68,   69,   68,   69,   75,  152,   80,
       84,  104,   88,  106,   76,   85,   90,   81,  198,  113,
       91,   96,  108,  110,   92,  144,  164,   97,   59,   82,

       59,  105,   86,   89,  166,  107,   93,   87,   70,   83,
       70,   98,   94,  109,  111,  242,   95,  145,  165,   99,
      113,  113,  113,   60,  167,   60,   78,  250,  113,  165,
      113,  279,  113,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,  165,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,  100,  167,  142,  168,  119,  113,  101,
      170,  276,  120,  113,  169,  292,  174,  171,  113,  113,
      113,  113,  113,  102,  167,  143,  113,  113,  169,  121,

      171,  103,  112,  122,  123,  113,  169,  171,  175,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  113,  112,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  114,  113,  113,  113,  113,  115,
      186,  113,  124,  172,  173,  175,  128,  116,  113,  125,
      129,  134,  146,  154,  130,  138,  176,  135,  147,  117,
      187,  139,  126,  150,  173,  173,  131,  175,  178,  118,
      127,  136,  132,  148,  113,  140,  133,  113,  177,  137,
      149,  113,  113,  141,  151,  177,  113,  179,  180,  182,

      179,  155,  113,  113,  113,  156,  113,  113,  113,  113,
      113,  157,  113,  190,  113,   74,  158,  177,  163,  179,
      181,  183,  181,  159,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,  183,  184,  181,  185,  187,  188,  189,  162,
      161,  113,   77,   74,   73,   72,   71,  305,   62,   62,
      305,  305,  305,  305,  183,  185,  187,  185,  189,  189,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      191,  192,  191,  192,  195,  196,  195,  196,  200,  200,

      305,  202,  203,  305,  202,  305,  305,  206,  203,  207,
      305,  192,  191,  194,  193,  196,  195,  199,  197,  206,
      200,  201,  202,  207,  203,  204,  113,  113,  113,  206,
      205,  207,  113,  113,  210,  211,  210,  305,  211,  214,
      113,  208,  214,  216,  217,  209,  305,  220,  113,  216,
      217,  222,  305,  220,  113,  223,  210,  211,  212,  113,
      213,  214,  224,  216,  215,  225,  217,  113,  220,  218,
      113,  223,  219,  226,  221,  223,  227,  228,  229,  230,
      113,  113,  231,  232,  225,  233,  234,  225,  235,  236,
      237,  238,  239,  227,  240,  241,  227,  229,  229,  231,

      243,  244,  231,  244,  243,  233,  247,  233,  235,  248,
      235,  237,  237,  239,  239,  252,  241,  241,  247,  248,
      243,  252,  254,  244,  245,  246,  247,  254,  255,  248,
      305,  255,  258,  258,  305,  113,  305,  252,  249,  251,
      260,  260,  254,  253,  262,  263,  305,  256,  262,  113,
      255,  263,  113,  257,  258,  259,  113,  113,  113,  266,
      274,  266,  260,  261,  268,  263,  262,  269,  113,  270,
      264,  265,  271,  275,  113,  272,  273,  277,  277,  282,
      275,  266,  113,  267,  280,  280,  269,  283,  113,  269,
      282,  271,  305,  275,  271,  286,  273,  273,  283,  277,

      278,  282,  286,  288,  280,  281,  289,  293,  283,  290,
      291,  294,  284,  113,  293,  286,  113,  294,  297,  285,
      305,  298,  287,  299,  289,  299,  113,  289,  293,  291,
      291,  294,  301,  113,  302,  295,  303,  296,  303,  305,
      298,  305,  113,  298,  305,  299,  113,  300,  305,  113,
      305,  305,  305,  305,  302,  305,  302,  305,  303,  305,
      304,   56,   56,   56,   61,   61,   61,   63,   63,   63,
       67,   67,   67,  153,  153,  153,  160,  305,  160,   11,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305
    } ;

static yyconst flex_int16_t yy_chk[744] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    7,    8,    7,
        8,    7,    8,    9,    9,   10,   10,   27,  310,   31,
       32,   37,   33,   38,   27,   32,   34,   31,  122,  122,
       34,   35,   39,   40,   34,   50,   80,   35,    3,   31,

        4,   37,   32,   33,   81,   38,   34,   32,    9,   31,
       10,   35,   34,   39,   40,  190,   34,   50,   80,   35,
       50,  304,  190,    3,   81,    4,   30,  198,  296,   82,
      198,  250,  250,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   82,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   36,   83,   49,   84,   44,  292,   36,
       85,  242,   44,  287,   86,  276,   92,   87,  281,  276,
      242,  279,  278,   36,   83,   49,  265,  264,   84,   44,

       85,   36,   41,   44,   44,   49,   86,   87,   92,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,  261,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   43,
      108,  259,   45,   91,   94,   95,   46,   43,  251,   45,
       46,   47,   51,   59,   46,   48,   96,   47,   51,   43,
      108,   48,   45,   52,   91,   94,   46,   95,   97,   43,
       45,   47,   46,   51,   43,   48,   46,   45,   96,   47,
       51,   51,   47,   48,   52,   98,   48,   99,  100,  101,

       97,   59,   52,  249,  245,   59,  213,  212,  208,  143,
      131,   59,  127,  114,  113,   74,   59,   98,   70,   99,
      100,  101,  102,   59,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,  103,  106,  102,  107,  109,  110,  111,   66,
       65,   42,   28,   24,   21,   18,   16,   11,    6,    5,
        0,    0,    0,    0,  103,  106,  109,  107,  110,  111,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      115,  116,  117,  118,  119,  120,  121,  123,  124,  126,

        0,  129,  130,    0,  132,    0,    0,  134,  133,  135,
        0,  116,  115,  118,  117,  120,  119,  123,  121,  136,
      124,  126,  129,  137,  130,  132,  126,  133,  118,  134,
      133,  135,  123,  132,  138,  139,  140,    0,  141,  144,
      136,  136,  145,  146,  147,  137,    0,  150,  137,  148,
      149,  164,    0,  151,  140,  165,  138,  139,  140,  141,
      141,  144,  166,  146,  145,  167,  147,  145,  150,  148,
      149,  164,  149,  168,  151,  165,  169,  170,  171,  172,
      148,  151,  173,  174,  166,  175,  178,  167,  179,  184,
      185,  186,  187,  168,  188,  189,  169,  170,  171,  172,

      191,  192,  173,  194,  193,  174,  195,  175,  178,  196,
      179,  184,  185,  186,  187,  200,  188,  189,  197,  199,
      191,  201,  202,  192,  193,  194,  195,  204,  203,  196,
        0,  205,  207,  209,    0,  193,    0,  200,  197,  199,
      214,  215,  202,  201,  216,  217,    0,  204,  218,  197,
      203,  219,  199,  205,  207,  209,  205,  209,  204,  220,
      240,  221,  214,  215,  224,  217,  216,  225,  215,  230,
      218,  219,  231,  241,  218,  232,  233,  244,  246,  254,
      240,  220,  219,  221,  252,  253,  224,  255,  221,  225,
      256,  230,    0,  241,  231,  266,  232,  233,  257,  244,

      246,  254,  267,  270,  252,  253,  271,  282,  255,  272,
      273,  283,  256,  256,  284,  266,  253,  285,  288,  257,
        0,  289,  267,  293,  270,  295,  257,  271,  282,  272,
      273,  283,  297,  267,  298,  284,  299,  285,  300,    0,
      288,    0,  284,  289,    0,  293,  295,  295,    0,  285,
        0,    0,    0,    0,  297,    0,  298,    0,  299,    0,
      300,  306,  306,  306,  307,  307,  307,  308,  308,  308,
      309,  309,  309,  311,  311,  311,  312,    0,  312,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[74] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[73] =
    {   0,
       99,  103,  109,  118,  127,  136,  145,  155,  164,  170,
      176,  184,  200,  203,  206,  209,  221,  225,  235,  239,
      245,  250,  258,  261,  265,  275,  276,  280,  284,  288,
      292,  296,  300,  304,  308,  312,  316,  320,  324,  328,
      332,  336,  341,  346,  351,  356,  360,  364,  368,  372,
      378,  386,  387,  388,  389,  390,  391,  392,  393,  394,
      395,  396,  397,  398,  399,  400,  401,  402,  403,  404,
      406,  409
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
#line 3 "cool.flex"
#include <cool-parse.h>
#include <stringtab.h>
#include <utilities.h>

/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

unsigned int comment_depth = 0;

/*
 *  Add Your own definitions here
 */


/*
 * Define names for regular expressions here.
 */
#line 886 "cool-lex.cc"

#define INITIAL 0
#define STRING 1
#define DASH_COMMENT 2
#define COMMENT 3
#define STRING_ERROR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
/* %% [7.0] user's declarations go here */
#line 86 "cool.flex"


 /*
  *  String constants (C syntax)
  *  Escape sequence \c is accepted for all characters c. Except for 
  *  \n \t \b \f, the result is c.
  * escaped null char in a string
  *	long strings with escaped characters
  * null char in string [submission crashed on this input]
  * null and unescaped newline in string
  * unterminated string
  */
  
#line 1189 "cool-lex.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 680 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 73 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 73 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 74 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 99 "cool.flex"
{ 
								strcpy(string_buf, "");
								BEGIN(STRING);
							}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 103 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.symbol = stringtable.add_string(string_buf);
								BEGIN(INITIAL);
				    			return STR_CONST;
							}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 109 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + 1 >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								strcat(string_buf, "\b");							
							}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + 1 >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								strcat(string_buf, "\t");
							}							
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 127 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + 1 >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								strcat(string_buf, "\n");
							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 136 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + 1 >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								strcat(string_buf, "\f");
							}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 145 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + 1 >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								// printf("escaped char: %s\n", yytext);
								strcat(string_buf, yytext + 1);
							}							
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 155 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + 1 >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								strcat(string_buf, "\n");
							}		
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 164 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.error_msg = "Unterminated string constant";
								BEGIN(INITIAL);
								return ERROR;
							}							
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 170 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.error_msg = "String cannot contain escaped null byte";
								BEGIN(STRING_ERROR);
								return ERROR;								
							}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 176 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.error_msg = "String contains null character";
								BEGIN(STRING_ERROR);
								return ERROR;								
							}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 184 "cool.flex"
{
								curr_lineno = yylineno;
								if (strlen(string_buf) + strlen(yytext) >= MAX_STR_CONST) {
									cool_yylval.error_msg = "String constant too long";
									BEGIN(STRING_ERROR);
									return ERROR;
								}
								// printf("yytext: %s\n", yytext + 1);
								strcat(string_buf, yytext);								
							}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 194 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.error_msg = "String cannot contain EOF";
								BEGIN(INITIAL);
								return ERROR;
							}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 200 "cool.flex"
{
								BEGIN(INITIAL);
							}							
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 203 "cool.flex"
{
								BEGIN(INITIAL);
							}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 206 "cool.flex"
{
								// do nothing
							}							
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 209 "cool.flex"
{
								// do nothing
							}
	YY_BREAK
case YY_STATE_EOF(STRING_ERROR):
#line 212 "cool.flex"
{
								BEGIN(INITIAL);
							}																					
	YY_BREAK
/*
  * COMMENTS
  */							
case 17:
YY_RULE_SETUP
#line 221 "cool.flex"
{								
								curr_lineno = yylineno;
								BEGIN(DASH_COMMENT);
							}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 225 "cool.flex"
{								
								curr_lineno = yylineno;
								BEGIN(INITIAL);
							}
	YY_BREAK
case YY_STATE_EOF(DASH_COMMENT):
#line 229 "cool.flex"
{		
								// printf("EOF dash_comment");						
								curr_lineno = yylineno;
								BEGIN(INITIAL);
								
							}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 235 "cool.flex"
{
								// printf("dash_comment\n");
								// DO nothing								
							}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 239 "cool.flex"
{
								// printf("--star comment\n");
								comment_depth++;
								curr_lineno = yylineno;
								BEGIN(COMMENT);
							}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 245 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.error_msg = "Unmatched *)";
								BEGIN(INITIAL);
							}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 250 "cool.flex"
{
								// printf("--end comment!\n");
								curr_lineno = yylineno;
								comment_depth--;
								if (comment_depth == 0) {
									BEGIN(INITIAL);
								}
							}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 258 "cool.flex"
{
								comment_depth++;
							}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 261 "cool.flex"
{ 
								// printf("--skip line\n");
								curr_lineno++;
							}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 265 "cool.flex"
{
								
							}
	YY_BREAK
/*
  * KEYWORDS
  */
case 26:
YY_RULE_SETUP
#line 275 "cool.flex"
{ curr_lineno = yylineno; return CLASS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 276 "cool.flex"
{
								curr_lineno = yylineno;
								return ELSE;
							}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 280 "cool.flex"
{
								curr_lineno = yylineno;
								return FI;
							}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 284 "cool.flex"
{
								curr_lineno = yylineno;
								return IF;
							}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 288 "cool.flex"
{
								curr_lineno = yylineno;
								return IN;
							}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 292 "cool.flex"
{
								curr_lineno = yylineno;
								return INHERITS;
							}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 296 "cool.flex"
{
								curr_lineno = yylineno;
								return LET;
							}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 300 "cool.flex"
{
								curr_lineno = yylineno;
								return LOOP;
							}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 304 "cool.flex"
{
								curr_lineno = yylineno;
								return POOL;
							}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 308 "cool.flex"
{
								curr_lineno = yylineno;
								return THEN;
							}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 312 "cool.flex"
{
								curr_lineno = yylineno;
								return WHILE;
							}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 316 "cool.flex"
{
								curr_lineno = yylineno;
								return CASE;
							}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 320 "cool.flex"
{
								curr_lineno = yylineno;
								return ESAC;
							}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 324 "cool.flex"
{
								curr_lineno = yylineno;
								return OF;
							}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 328 "cool.flex"
{
								curr_lineno = yylineno;
								return NEW;
							}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 332 "cool.flex"
{
								curr_lineno = yylineno;
								return ISVOID;
							}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 336 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.boolean = true;
								return BOOL_CONST;
							}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 341 "cool.flex"
{
								curr_lineno = yylineno;
								cool_yylval.boolean = false;
								return BOOL_CONST;
							}							
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 346 "cool.flex"
{ 
								curr_lineno = yylineno;
								cool_yylval.symbol = stringtable.add_string(yytext);
								return TYPEID;
							}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 351 "cool.flex"
{ 
								curr_lineno = yylineno;
								cool_yylval.symbol = stringtable.add_string(yytext);
								return OBJECTID; 
							}								
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 356 "cool.flex"
{
								curr_lineno = yylineno;
								return ASSIGN;
							}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 360 "cool.flex"
{
								curr_lineno = yylineno;
								return NOT;
							}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 364 "cool.flex"
{
								curr_lineno = yylineno;
								return LE;
							}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 368 "cool.flex"
{
								curr_lineno = yylineno;
								return ERROR;
							}																																			
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 372 "cool.flex"
{
								curr_lineno = yylineno;
								return LET_STMT;
							}																																			
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 378 "cool.flex"
{ 
								curr_lineno = yylineno;
								cool_yylval.symbol = inttable.add_string(yytext);
								return INT_CONST; 
							}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 386 "cool.flex"
{ curr_lineno = yylineno; return DARROW; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 387 "cool.flex"
{  curr_lineno = yylineno;  return ASSIGN;    } 	
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 388 "cool.flex"
{  curr_lineno = yylineno;  return int('+');  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 389 "cool.flex"
{  curr_lineno = yylineno;  return int('/');  }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 390 "cool.flex"
{  curr_lineno = yylineno;  return int('-');  }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 391 "cool.flex"
{  curr_lineno = yylineno;  return int('*');  }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 392 "cool.flex"
{  curr_lineno = yylineno;  return int('=');  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 393 "cool.flex"
{  curr_lineno = yylineno;  return int('<');  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 394 "cool.flex"
{  curr_lineno = yylineno;  return LE;        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 395 "cool.flex"
{  curr_lineno = yylineno;  return int('.');  }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 396 "cool.flex"
{  curr_lineno = yylineno;  return int('~');  }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 397 "cool.flex"
{  curr_lineno = yylineno;  return int(',');  }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 398 "cool.flex"
{  curr_lineno = yylineno;  return int(';');  }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 399 "cool.flex"
{  curr_lineno = yylineno;  return int(':');  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 400 "cool.flex"
{  curr_lineno = yylineno;  return char('(');  }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 401 "cool.flex"
{  curr_lineno = yylineno;  return char(')');  }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 402 "cool.flex"
{  curr_lineno = yylineno;  return int('@');  }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 403 "cool.flex"
{  curr_lineno = yylineno;  return int('{');  }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 404 "cool.flex"
{  curr_lineno = yylineno;  return int('}');  }
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 406 "cool.flex"
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 409 "cool.flex"
{ 
								curr_lineno = yylineno;
								cool_yylval.error_msg = yytext;
								return ERROR;
							}
	YY_BREAK
/*
  *  The multiple-character operators.
  */
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
case 73:
YY_RULE_SETUP
#line 431 "cool.flex"
ECHO;
	YY_BREAK
#line 1893 "cool-lex.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 63);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 63;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 305);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 431 "cool.flex"



